name: main → release

on: workflow_dispatch

jobs:
  merge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.TOKEN_REPO }}

      - name: Set up Git identity
        run: |
          git config user.email bryndyment@gmail.com
          git config user.name "Bryn Dyment"
          
      - name: Merge and push
        run: |
          git checkout release
          git merge main --no-edit
          git push
