name: main → release

on: workflow_dispatch

jobs:
  main-to-release:
    runs-on: ubuntu-latest

    steps:
      - name: Enforce `main` branch
        run: |
          if [ "${{ github.event.ref }}" != 'refs/heads/main' ]; then
            echo 'Error: workflow can only be used from `main` branch'
            exit 1
          fi
          echo '✔'

      - name: Check out `main` branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_REPO }}

      - name: Recreate `release` branch
        run: |
          git push origin -d release || true
          git checkout -b release
          git push -u origin release
