name: main → release

on: workflow_dispatch

jobs:
  main-to-release:
    runs-on: ubuntu-latest

    steps:
      - name: Enforce `main` branch
        run: |
          if [ "${{ github.event.ref }}" != 'refs/heads/main' ]; then
            echo 'Error: workflow can only be used from `main` branch'
            exit 1
          fi

      - name: Check out `main` branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_REPO }}

      - name: Update `release` branch
        run: |
          git checkout release
          git merge --ff-only origin/main
          git push origin release
